qemu-demo-start: add configuration file support.
The demo configurations are not longer hard-coded in the script, but
read from a configuration file, which default location is
$HOME/.config/qemu-demo-start.conf.

diff --git a/scripts/qemu-demo-start b/scripts/qemu-demo-start
--- a/scripts/qemu-demo-start
+++ b/scripts/qemu-demo-start
@@ -1,15 +1,28 @@
-#!/bin/sh
+#!/bin/bash
 #
-# qemu-start-demo - Starts QEMU virtual machines
+# qemu-start-demo - Starts a QEMU virtual machine with demo image
 #
 # Copyright (c) 2014 Eric Le Bihan <eric.le.bihan.dev@free.fr>
 #
 # This project is released under the MIT/X11 license.
 #
 
-__VERSION__=0.1.0
+#
+# This program starts a QEMU virtual machine with a kernel and a root file
+# system generated by Buildroot. The available images should be listed in a
+# configuration file, where each line is formatted as follow:
+#
+#   arch koptions demo comment
+#
+# If no kernel options are needed, set koptions to 'x'.
+#
+# The default configuration file is $HOME/.config/qemo-demo-start.conf
+#
 
-IMAGE_DIR="${HOME}/build/elebihan"
+__VERSION__=0.2.0
+
+CONFIG_FILE=$HOME/.config/qemu-demo-start.conf
+IMAGE_DIR="${HOME}/build"
 QEMU_SYSTEM_X86="qemu-system-i386 --enable-kvm"
 QEMU_SYSTEM_ARM="qemu-system-arm -m 256"
 LINUX_CONSOLE=
@@ -27,71 +40,12 @@ Usage: $(basename $0) [OPTIONS] <ARCH> <TOPIC>
 
 Options:
 
+  -c FILE:    set path to configuration file
   -k COMMAND: set kernel command line
   -i DIR:     set image path to DIR
   -n:         do not start graphical interface
   -u VID:PID  attach USB device specified by its VID and PID
 EOF
-}
-
-start_qemu_x86_misc() {
-	start_qemu_x86 "misc" "Starting Misc Demo on QEMU x86"
-}
-
-start_qemu_x86_runit() {
-	start_qemu_x86 "runit" "Starting Runit Demo on QEMU x86"
-}
-
-start_qemu_x86_gtk3_x11() {
-	start_qemu_x86 "gtk3-x11" "Starting Gtk+ 3.0 (X11) Demo on QEMU x86"
-}
-
-start_qemu_x86_qt5() {
-	start_qemu_x86 "qt5" "Starting Qt5 Demo on QEMU x86"
-}
-
-start_qemu_x86_gtk3_wayland() {
-	start_qemu_x86 "gtk3-wayland" "Starting Gtk+ 3.0 (Wayland) Demo on QEMU x86"
-}
-
-start_qemu_x86_pygtk() {
-	start_qemu_x86 "pygtk" "Starting PyGtk Demo on QEMU x86"
-}
-
-start_qemu_x86_systemd() {
-	start_qemu_x86 "systemd" "Starting Systemd Demo on QEMU x86"
-}
-
-start_qemu_x86_eudev() {
-	start_qemu_x86 "eudev" "Starting Eudev Demo on QEMU x86"
-}
-
-start_qemu_x86_grsec() {
-	start_qemu_x86 "grsec" "Starting Grsecurity Demo on QEMU x86"
-}
-
-start_qemu_x86_smack() {
-	start_qemu_x86 "smack" "Starting SMACK Demo on QEMU x86"
-}
-
-start_qemu_arm_systemd() {
-	start_qemu_arm "systemd" "Starting Systemd Demo on QEMU ARM"
-}
-
-start_qemu_arm_eudev() {
-	start_qemu_arm "eudev" "Starting Eudev Demo on QEMU ARM"
-}
-
-start_qemu_arm_gtk3_x11() {
-	start_qemu_arm "gtk3-x11" "Starting Gtk+ 3.0 (X11) Demo on QEMU ARM"
-}
-
-start_qemu_arm_gtk3_wayland() {
-	start_qemu_arm "gtk3-wayland" "Starting Gtk+ 3.0 (Wayland) Demo on QEMU ARM"
-}
-
-start_qemu_arm_pygtk() {
-	start_qemu_arm "pygtk" "Starting PyGtk Demo on QEMU ARM"
 }
 
 start_qemu_x86() {
@@ -127,10 +81,13 @@ start_qemu_arm() {
 	-device usb-storage,drive=my_usb_stick
 }
 
-while getopts "hvk:i:nu:" option; do
+while getopts "hvc:k:i:nu:" option; do
 	case $option in
 		h)
 			usage; exit 0
+			;;
+		c)
+			CONFIG_FILE=${OPTARG}
 			;;
 		k)
 			LINUX_OPTS=${OPTARG}
@@ -170,8 +127,21 @@ if [ -n "${QEMU_OPTS_USB}" ]; then
 	QEMU_OPTS="${QEMU_OPTS} ${QEMU_OPTS_USB}"
 fi
 
-ARCH=$1
-DEMO=$(echo $2 | tr '-' '_')
+COMMAND=
+while read arch options demo comment; do
+	if [ "$1" = "${arch}" -a "$2" = "${demo}" ]; then
+		COMMAND="start_qemu_${arch} ${demo}"
+		COMMENT="Starting ${comment}..."
+		if [ "${options}" != "x" ]; then
+			LINUX_OPTS="${LINUX_OPTS} ${options}"
+		fi
+	fi
+done < ${CONFIG_FILE}
 
-COMMAND="start_qemu_${ARCH}_${DEMO}"
+if [ -z "${COMMAND}" ]; then
+	echo "Error: configuration not found." 2>&1
+	exit 3
+fi
+
+echo ${COMMENT}
 eval ${COMMAND}
